### ISSUE TITLE
POE Trades Companion is flagged by windows defender as a trojan

### ISSUE THREAD

**Issue by gdneye** [POE-Addon-Launcher/PAL2#10]
*See screenshot*

There is an open issue/PSA on the trades-companion website.  

https://github.com/lemasato/POE-Trades-Companion/issues/124

Since 
1) trades companion is frequently used by POE players, many of whom are much more knowledgeable than me about security risks and
2) He is pretty upfront about the issue and none of the comments seem to be disagreeing with his explanation

I am inclined to believe the program is ok.  But I still thought it might be a good idea to mention it over here as looking for verification that a program is safe on its own Github seems a bit tautological.  

Assuming it is perfectly safe, maybe it would be worth somehow letting PAL users know that this might occur.  I had a mild heart attack when the warning that I have a Trojan popped up.

![poe trades companion trojan](https://user-images.githubusercontent.com/26702989/53582288-13bfe180-3b77-11e9-8018-339dd7541a46.png)

**Comment by POE-Addon-Launcher** [comment]
Technically there is a message for that in settings, but yeah maybe I could add something more clear.

**Comment by lemasato** [comment]
Is PAL using the executable?
I've been adding .zip that contains only AHK for a while now, specifically because for this issue. Anyway, the executable is bound to disappear completely in the future.
It would be best if PAL could start using the AHK zip instead.

**Comment by POE-Addon-Launcher** [comment]
Noted, will add a TODO in my project to do so.

**Comment by POE-Addon-Launcher** [comment]
See: https://github.com/POE-Addon-Launcher/PAL2/issues/6
