### ISSUE TITLE
 [FIXED] - Java Runtime error

### ISSUE THREAD

**Issue by GlowingShadow** [POE-Addon-Launcher/PAL2#18]
Hello,

Today i had an error launching PAL2:

> includes evaluation version of Java Runtime not eligible for distribution.

Do i have to do something to solve this ?

**Comment by Llywynn** [comment]
That would be awesome to know as I got the same problem as of today.

**Comment by Pekno** [comment]
Same here, isn't the App supposed to be rewritten in Kotlin ( so no more Java ) ?

**Comment by webbdaddy** [comment]
same issue here.

**Comment by ocombe** [comment]
Same thing since this morning

**Comment by the24thour** [comment]
Indeed cant launch program with out this error. Java does it again!

**Comment by vangiers** [comment]
Same issue

**Comment by MildanWorld** [comment]
> Hello,
> 
> Today i had an error launching PAL2:
> 
> > includes evaluation version of Java Runtime not eligible for distribution.
> 
> Do i have to do something to solve this ?

No, from the error message it seems like the new update was wrongly deployed somehow.

Oracle has changed the Java licenses for 2019, and most updates for Java 8 (which it seems this addon runs on) which will require a fee to distribute. However this project should be non-commercial, so the java distributed runtime probably just needs updating to work again, since the license fees do not apply for these.

**Comment by steffektif** [comment]
@Pekno Kotlin is also a JVM language which means that its requires a Java runtime environment (JRE) to run.

**Comment by TokiSilvertongue** [comment]
Is there any idea for an ETA on the updated version which works?

**Comment by RDK3j** [comment]
same problem there fix this!

**Comment by dgideon** [comment]
While we wait for a updated release I thought this might help some folks who want to still run their addons that are usually managed by PAL2.

PAL2 has most of the addons in one of two locations. You must have Windows show "hidden folders" **or** go to your search bar (usually next to the "start" button/logo in the bottom left hand corner of your screen) and type %appdata% and press enter. Then proceed to navigate to:

C:\Users\yourfolder\AppData\Local\PAL\Addons

C:\Users\yourfolder\AppData\Local\Programs

Obviously, "yourfolder" above is going to be different for each computer and the user account setup on it that you are logged into.

Now just go to each of the Addon folders and look for their shortcut to manually start the program/script.

Hope this helps someone!

**Comment by POE-Addon-Launcher** [comment]
Update coming in a few minutes, gonna repack and then it will break again in 90 days, I've e-mailed Excelsior JET to get a possible Free License so that it won't happen again, sorry for the inconvience!

NOTE:
You'll have to manually update to v1.0.8 
This means replacing all of the files where you installed it.

**Comment by POE-Addon-Launcher** [comment]
Fixed, download: https://github.com/POE-Addon-Launcher/PAL2/releases/download/1.0.8/PAL2.zip replace the contents of your installation, won't auto-update!

**Comment by ocombe** [comment]
Thanks for the quick fix!

**Comment by Adjunify** [comment]
Thank you so very much for the quick fix!  Also, thank you for creating this program for us.  I use it daily and appreciate your hard work.

**Comment by TokiSilvertongue** [comment]
Amazing! Love the work you do <3

**Comment by RDK3j** [comment]
<3

**Comment by dy1ng** [comment]
I'm having the same issue today. Does the app need to be updated again?

**Comment by haggygt** [comment]
This is happening again

**Comment by Cefwyn** [comment]
Yeah, requires a fix again.

**Comment by projectsix84** [comment]
Yep, having the same issue today. An update would be much appreciated.

**Comment by Frogmastr** [comment]
damn java

**Comment by emiliodacosta** [comment]
womp womp

**Comment by btrams** [comment]
sadface. i'm dependent now, why have you done do this. jk love the launcher hope it gets fixed again soon

**Comment by ocombe** [comment]
Thanks for the quick update !
