### ISSUE TITLE
Improve custom AHK support

### ISSUE THREAD

**Issue by PsychicMuffin** [POE-Addon-Launcher/PAL2#19]
Currently we can add custom AHKs, but can't really interact with them the same way we can with normal addons. For instance we can't:
* Launch them manually
* Enable/Disable them
* Configure them (only relevant for launch command in case you change AHK install directory or something)

It would be nice to be able to use them like normal addons, and not have to go remove/re-add them if I want to disable it temporarily, or accidentally close it and have to go into the file system to launch it.

**Comment by POE-Addon-Launcher** [comment]
Good suggestions, I'm gonna think of some way to neatly add this.

**Comment by POE-Addon-Launcher** [comment]
Currentlly being worked on, releasing soon(tm)
