### ISSUE TITLE
Stuck on "Booting up PAL"

### ISSUE THREAD

**Issue by mikan9** [POE-Addon-Launcher/PAL2#20]
When launching PAL2 (with or without admin privileges) it gets stuck on "Booting up PAL", the main window is however still accessible, except for the fact that when you enter the menu with About, AutoHotKey, Disclaimer tabs you're unable to go back out to the main layout.

There's also no PAL folder generated in AppData/Local and the log file, although generated is empty.

Also added exceptions to my firewall and antivirus application, to no avail.

EDIT: Tried running PAL2 on another computer, this time the configuration window loaded up and I was able to set everything up without any problems. Still can't figure out why it refuses to work on my main computer though. Both are running Windows 10 Pro x64 with JRE & JDK 8 installed.

**Comment by gcc88879712** [comment]
i have exactly issue like this, hope it will be solved soon

**Comment by POE-Addon-Launcher** [comment]
Is it in a folder that requires administrative privileges?

**Comment by POE-Addon-Launcher** [comment]
No input from anyone involved, closing for now.
