### ISSUE TITLE
Loot Filters can't be downloaded and updated

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [POE-Addon-Launcher/PAL2#22]

**Comment by throwgithub** [comment]
We will be able to add Neversink's Loot Filter as "addon" and PAL2 will keep it up to date? In that case PAL2 would be able to manage every additional tool you "need" to play PoE! That would be absolutely amazing!

**Comment by POE-Addon-Launcher** [comment]
Yeah you can do that right now, well for the most part.
