### ISSUE TITLE
Unable to get downloads to start.

### ISSUE THREAD

**Issue by Lward95** [POE-Addon-Launcher/PAL2#3]
https://gfycat.com/GorgeousDefiniteChick

**Comment by Adiwcs** [comment]
i have the same issue, tried running in admin mode too

**Comment by CMetaPhor** [comment]
sadly it's the same for me :(

**Comment by kittiesgomeww** [comment]
Same issue as well

**Comment by POE-Addon-Launcher** [comment]
This should be resolved now anyone have any updates?

**Comment by Lward95** [comment]
Appears to have fixed it, Thank you.

**Comment by RyujinDoji** [comment]
Max download speed for PAL2 8,5 KB/s
Known Issue?

**Comment by POE-Addon-Launcher** [comment]
@RyujinDoji I'm downloading at 20mb/s so, I'm not sure what's up, with that.
