### ISSUE TITLE
Addon: POE-Trades-Companion auto updater broken

### ISSUE THREAD

**Issue by sicu** [POE-Addon-Launcher/PAL2#46]
The 2 latest releases of POE-Trades-Companion (1.15.BETA_1 and 1.15.BETA_2) state that they require a manual download as the auto-updater is now broken for versions pre-1.15

**Comment by POE-Addon-Launcher** [comment]
Yeah, I don't use their auto-updater the issue is that they marked it as a pre-release, if they'd mark it as a non pre-release PAL would just grab their update.

**Comment by sicu** [comment]
Ah, thank you for the clarification. I'll just update manually until it gets back to regular release. Great work on the launcher btw :)
