### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by DjaeCG** [POE-Addon-Launcher/PAL2#5]
Stuck at loading screen "Booting up PAL,waiting on configurator"

**Comment by MyGg29** [comment]
Same for me. 
On my first installation, I closed a window by mistake. (I think it's one where I'm suposed to put some path to some folder).
Now when I run the installer again, the same windows doesn't open anymore. 
I restarted my pc to see if it was a process running in the background, but it doesn't help.

**Comment by ImNorcal** [comment]
Same problem here. Waiting on configurator.

**Comment by kraven40** [comment]
open a windows run window (windowskey + R) enter this:

%localappdata%/pal

Now delete the "Data" folder

Try to launch it again and it should allow you to reconfigure

**Comment by POE-Addon-Launcher** [comment]
Yes, that is the solution I recommend to everyone, gonna leave this open for the future.

**Comment by Noltop** [comment]
Im having the same problem however I dont have a pal folder in AppData

https://i.imgur.com/uVcVBKI.png

**Comment by vith** [comment]
@Noltop Your screenshot is `AppData\Roaming` but you need to look in `AppData\Local`
