### ISSUE TITLE
v1.12.2 does not start after init script

### ISSUE THREAD

**Issue by Adamih** [POE-Addon-Launcher/PAL2#53]
After it's script is started, the .jar is created and the script claims it is installed, nothing happens. Are there any logs to debug this on 1.12? This is the first time i download and install PAL2. PAL1 worked fine for me.

**Comment by emeria-zz** [comment]
I think this app is broken until the expired license is fixed.

I did the manual fix,   but the PAL2 app never worked correctly again.

**Comment by POE-Addon-Launcher** [comment]
If you've had PAL1 installed you can just run the jar and the program will work fine for you.

The exe is only there to update the program and make sure you have jvm binaries.

Incase you're wondering where to find the JARs they're here:
https://github.com/POE-Addon-Launcher/PALRelease/releases

**Comment by emeria-zz** [comment]
> If you've had PAL1 installed you can just run the jar and the program will work fine for you.
> 
> The exe is only there to update the program and make sure you have jvm binaries.
> 
> Incase you're wondering where to find the JARs they're here:
> https://github.com/POE-Addon-Launcher/PALRelease/releases

Thanks, I will give this a try tonight!

**Comment by Adamih** [comment]
Now everything just works for some reason. Fantastic!
