### ISSUE TITLE
PAL2 Won't launch at all (nothing happens).

### ISSUE THREAD

**Issue by WlcxDev** [POE-Addon-Launcher/PAL2#54]
I downloaded the new version, double clicked the .exe, It downloaded a .jar file and JRE. Double clicking on the .jar does absolutely nothing.

**Comment by MechTrap** [comment]
For me it ONLY launches, if it's in the download Folder, whenever I put it into another folder it won't launch, kinda inconvenient since I regularily clear my download folder.

**Comment by toma1600** [comment]
I'm having the exact same issue.

**Comment by ofbeaton** [comment]
Same here. It only launches from the original place I launched it from. I thought it was an installed so I launched from my temporary downloads folder... now it only works if I launch from there. 

I copied it elsewhere and it downloads the jar then does nothing (flashes a console window).

**Comment by savicaleksa** [comment]
Installing/updating Java should help. I had the same problem and when i installed Java it started working again
