### ISSUE TITLE
POE-Trades-Companion doesn't download properly

### ISSUE THREAD

**Issue by crimory** [POE-Addon-Launcher/PAL2#6]
For some reason _POE TradeMacro_ and _Path of Building_ both work fine, but _POE-Trades-Companion_ doesn't.

Steps to reproduce:
1. click _Download_ for _POE-Trades-Companion_
2. it downloads (creates the folder, but the folder is empty)
3. click on _Installed tab_ - _POE-Trades-Companion_ is not listed there
4. restart _PAL2_
5. _Download_ button for _POE-Trades-Companion_ available again to be pressed (effect is the same)

Note:
I downloaded _POE-Trades-Companion_ from github and unpacked it to folder created in step 2, but _PAL2_ still doesn't see the _POE-Trades-Companion_

**Comment by crimory** [comment]
I just realised, that it probably have something to do with POE-Trades-Companion latest release info:
> Download POE-Trades-Companion-AHK.zip if the executable is being flagged by your antivirus. Extract the zip and run POE Trades Companion.ahk. You do not need to compile the script, you can simply run the ahk file just like you would do with TradeMacro.

For me - I have to use the *.ahk script, but PAL2 tries to use the *.exe file - that's my guess.

**Comment by POE-Addon-Launcher** [comment]
I'll investigate and make it grab the AHK instead.

**Comment by dhimelick** [comment]
That definitely seems to be the issue. I was able to resolve this by adding exclusions in Windows Defender Security Center for the PAL temp_downloads folder and the POE-Trades-Companion Addon folder.
