### ISSUE TITLE
League Overlay

### ISSUE THREAD

**Issue by gitrulez** [POE-Addon-Launcher/PAL2#7]
Please add League Overlay. It is an AHK script that shows cheat sheets for Syndicate, Incursion, Fossils and Atlas, so you don't nede to alt-tab. 
https://github.com/heokor/League-Overlay

**Comment by POE-Addon-Launcher** [comment]
Added support
https://github.com/POE-Addon-Launcher/PAL2/commit/7817288b266ae875f7d0637aae19be346708a0cd

**Comment by gitrulez** [comment]
Many thanks for adding it! But I cant get PAL2 to launch it together with PoE. The following error always appears:
![pal2-league-overlay](https://user-images.githubusercontent.com/9252298/53283346-5c296a80-3745-11e9-909a-461c3bde1902.png)
When I start PoE first without any addons, and then launch League Overlay by double clicking in the PAL2 "Installed" tab, it works. But it does not work automatically when clicking "Launch Path of Exile".
EDIT: attached logfile: [PAL_Logger.log](https://github.com/POE-Addon-Launcher/PAL2/files/2896594/PAL_Logger.log)
