### ISSUE TITLE
Github API seems to be offline

### ISSUE THREAD

**Issue by niklasschaeffer** [POE-Addon-Launcher/PAL2#70]
Seems weird Github Api is there. There is also nothing on my end that blocks the connection though.

`2020-13-01 11:13:47.830 [DefaultDispatcher-worker-5] ERROR Github.GH_Connector - Github API is likely offline, retrying in 5 seconds!`

**Comment by alexbergsland** [comment]
I have this too.
Although in my case I just updated the access token for PAL.
Not really sure how to fix that when the app wont launch, it is stuck on "Booting up PAL, Checking for Updates to PAL"
