### ISSUE TITLE
Font looks small/bad on ultrawide resolution

### ISSUE THREAD

**Issue by sadboicozy** [POE-Addon-Launcher/PAL2#8]
I use a 3440x1440p ultrawide monitor, and the font looks really off in PAL2. The letters aren't smooth at all and the font seems too small to be legible. Maybe the type doesn't jive with 1440p?

Example images attached.

![image](https://user-images.githubusercontent.com/6015095/52993218-4ecc5300-33c8-11e9-9731-48394c27f1db.png)
![image](https://user-images.githubusercontent.com/6015095/52993222-52f87080-33c8-11e9-8dd8-d6b5c8f5280b.png)

**Comment by POE-Addon-Launcher** [comment]
I also use a 3440x1440 monitor and it looks fine here.

I don't think it's a resolution issue.

**Comment by sadboicozy** [comment]
Do you have any idea how I could troubleshoot this, then? There are no font options/settings I could see within the program; is this pulling directly from a Windows default font, or setting one somewhere?

**Comment by POE-Addon-Launcher** [comment]
Small update to this in 1.10, should fix it.
