### ISSUE TITLE
MercuryTrade does not launch

### ISSUE THREAD

**Issue by gitrulez** [POE-Addon-Launcher/PAL2#9]
MercuryTrade does never launch, also not when double clicking it manually. There is no error or anything. 
Starting it outside of PAL2 by downloading and clicking the JAR file works fine.
Attached the logfile (removed my username and github token):
[PAL_Logger.log](https://github.com/POE-Addon-Launcher/PAL2/files/2896592/PAL_Logger.log)

**Comment by throwgithub** [comment]
Same issue here.

**Comment by POE-Addon-Launcher** [comment]
Seems to be working now?
